build:
  build_starting:
    image: python:2
    commands:
      - echo "Beginning new build"

publish:
    docker:
        repo: $$DOCKER_USERNAME/c2k_listener
        tag: latest
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL 

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/c2k/c2klistener/restart?force=true

